# Generated by Django 3.2.5 on 2021-07-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelExperienceApp', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
