# Generated by Django 3.2.5 on 2021-07-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelExperienceApp', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
