# Generated by Django 3.2.5 on 2021-07-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelExperienceApp', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
