# Generated by Django 3.2.5 on 2021-07-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelExperienceApp', '0011_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=12, upload_to='images'),
            preserve_default=False,
        ),
    ]
